kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-inventory
subjects:
- kind: ServiceAccount
  name: multicluster-inventory
roleRef:
  kind: Role
  name: multicluster-inventory
  apiGroup: rbac.authorization.k8s.io
